---
- name: install zabbix server
  yum: name=zabbix state=present

- name: install zabbix server mysql
  yum: name=zabbix-server-mysql state=present

- name: configure zabbix server
  template: src=zabbix/zabbix_server.conf.j2 dest=/etc/zabbix/zabbix_server.conf owner=root group=zabbix mode=0640
  notify: restart zabbix server

- name: enable zabbix server
  service: name=zabbix-server enabled=yes
  notify: restart zabbix server

- name: configure firewall for zabbix
  firewalld: zone=public port=10051/tcp permanent=true state=enabled
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 7
